11 Home work
vvforever/Python_Pro pull request #2
Opened 2022-05-10 11:35 UTC by vvforever

2022-05-11 07:14 UTC, 0x55AAh commented on 11-lesson/11.py
> +def cached():
Так как декоратор у нас не принимает никаких аргументов, то в принципе нет смысла в этом лишнем слое.

2022-05-11 09:55 UTC, vvforever commented on 11-lesson/11.py
> +            key = args
Буде використане одне і теж саме значення функції з кешу. Це моя помилка. Тоді треба якось зберігати kwargs. Як це можна зробити?

2022-05-27 18:51 UTC, 0x55AAh requested changes

2022-05-27 18:51 UTC, 0x55AAh commented on 12-lesson/12.py
> +    def __gt__(self, other):
Нет смысла делать магические методы абстрактными. Но есть смысл реализовать их используя `square` и `perimeter`.

2022-05-27 18:51 UTC, 0x55AAh commented on 12-lesson/12.py
> +        """
Хорошая и исчерпывающая документация.

2022-05-27 18:51 UTC, 0x55AAh commented on 12-lesson/12.py
> +        return math.ceil(self.perimeter())
Вот это вполне можно разместить в родительском абстрактном классе. Тогда не придется его дублировать для остальных классов.

2022-05-27 18:51 UTC, 0x55AAh commented on 12-lesson/12.py
> +    def __add__(self, other):
То же самое. Просмотрите и остальные методы волшебные методы.

2022-05-31 11:46 UTC, vvforever commented on 12-lesson/12.py
> +    def __add__(self, other):
Переніс всі магічні методи до батьківського класу

2022-06-02 11:33 UTC, merged